In [168]:
# 1. LISTS
# 1.1 Lists

In [169]:
aList = ["Anayah Hanifah E.", 19, "Tangerang", True]

In [170]:
aList 

['Anayah Hanifah E.', 19, 'Tangerang', True]

In [171]:
type(aList)

list

In [172]:
#2. TUPLES (Tuples)

In [173]:
bin_colors = ('Red','Green','Blue','Yellow')
print(f"The second element of the tuple is {bin_colors[1]}")

The second element of the tuple is Green


In [174]:
print(f"The element after thrid element onewards are {bin_colors[2:]}")
print("Ini adalah data tipe : ",type(bin_colors))

The element after thrid element onewards are ('Blue', 'Yellow')
Ini adalah data tipe :  <class 'tuple'>


In [175]:
# let us define neested tuple data structure

In [176]:
nested_tuple = (1,2,(100,200,400),6)
print(f"The maximum value of the inner tuple {max(nested_tuple[2])}")

The maximum value of the inner tuple 400


In [177]:
# 3. DICTIONARY
# 1.2 Dictionary

In [178]:
bin_colors = {
    "manual_color": "Yellow",
    "approved_color": "Green",
    "refused_color": "Red"
}

In [179]:
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [180]:
bin_colors.get('approved_color')

'Green'

In [181]:
bin_colors['approved_color']

'Green'

In [182]:
bin_colors['approved_color']="Purple" #memberikan data baru ke pada 'approved_color' yakni menjadi 'purple'

In [183]:
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


In [184]:
# 4 SETS
#1.3 Set

In [185]:
green = {'grass', 'leaves'}
print(green)

{'grass', 'leaves'}


In [186]:
yellow = {'pisang', 'warna', 'payung'}
red = {'tomat', 'warna', 'payung', 'jerawat'}

In [187]:
print(f"The union of yellow and red sets is {yellow|red}")

The union of yellow and red sets is {'pisang', 'warna', 'tomat', 'payung', 'jerawat'}


In [188]:
print(f"The intersaction of yellow and red sets is {yellow&red}")

The intersaction of yellow and red sets is {'warna', 'payung'}


In [189]:
# 5. DATA FRAMES
# 1.4 DataFrame

In [190]:
import pandas as pd
df = pd.DataFrame([
    ['1','Anayah', 12, True],
    ['2','Hanifah', 22, False],
    ['3','Elsyaf', 32, True] ])
df.columns = ['id', 'name', 'age', 'decision']
print(df)

  id     name  age  decision
0  1   Anayah   12      True
1  2  Hanifah   22     False
2  3   Elsyaf   32      True


In [191]:
# 1.4.1 Column Selection

In [192]:
df [['name', 'age']]

name  age
0   Anayah   12
1  Hanifah   22
2   Elsyaf   32

In [193]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [194]:
# 1.4.2 Row Selection

In [195]:
df.iloc[1:3,:]

id     name  age  decision
1  2  Hanifah   22     False
2  3   Elsyaf   32      True

In [196]:
df[df.age>20] #data yang ditampilkan adalah data yang memiliki umur lebih dari 20

id     name  age  decision
1  2  Hanifah   22     False
2  3   Elsyaf   32      True

In [197]:
# 6. MATRIX
# 1.5 Matrix

In [198]:
import numpy as np
myMatrix = np.array([[11,12,13],[21,22,23],[31,32,33]])
myMatrix_two = np.array([[11,12,13],
                         [21,22,23],
                         [31,32,33]])

In [199]:
print(myMatrix)
print("\n")
print("Hasil akan tetap sama walaupun ditulis dengan cara yang berbeda",myMatrix_two)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


Hasil akan tetap sama walaupun ditulis dengan cara yang berbeda [[11 12 13]
 [21 22 23]
 [31 32 33]]


In [200]:
print(type(myMatrix)) # untuk memeriksa tipe class setelah array matrix diberikan numpy

<class 'numpy.ndarray'>


In [201]:
myMatrix.transpose()

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [202]:
# TIPE DATA ABSTRAK

In [203]:
# 1. VEKTOR

In [204]:
myVector = [22,33,44,55]
print(myVector)

[22, 33, 44, 55]


In [205]:
print(type(myVector))

<class 'list'>


In [206]:
myVector = np.array([22,33,44,55])
print(myVector)

[22 33 44 55]


In [207]:
print(type(myVector))

<class 'numpy.ndarray'>


In [208]:
# 2. STACK

In [209]:
class Stack:
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def push(self,item):
        self.items.append(item)
    def pop(self):
        return self.items.pop()
    def pook(self):
        return self.items[len(self.items)-1]
    def size(self):
        return len(self.items)

In [233]:
# POPULATE THE STACK
stack = Stack()
stack.push('Red')
stack.push('Green')
stack.push('Blue')
stack.push('Yellow')

In [234]:
# POP
stack.pop() #yang pertama keluar adalah yang pertama di input

'Yellow'

In [212]:
stack.isEmpty()

False

In [213]:
colors = ['Red']

In [214]:
colors.append('Green')
colors.append('Yellow')
colors.append('Blue')

In [215]:
colors

['Red', 'Green', 'Yellow', 'Blue']

In [216]:
# 3. QUEUE 

In [217]:
class Queue(object):
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def enqueue(self, item):
        self.items.insert(0,item)
    def dequeue(self):
        return self.items.pop()
    def size(self):
        return len(self.items)

In [218]:
queue = Queue()

In [219]:
queue.enqueue("Red")

In [220]:
queue.enqueue("Green")

In [221]:
queue.enqueue("Blue")

In [222]:
queue.enqueue("Yellow")

In [223]:
print(f"Size of queue is {queue.size()}") 

Size of queue is 4


In [224]:
print(queue.dequeue()) #yang di input terakhir keluar pertama

Red


In [225]:
print(queue.dequeue())

Green


In [226]:
print(queue.dequeue())

Blue


In [227]:
queue.isEmpty()

False

In [228]:
print(queue.dequeue())

Yellow


In [230]:
queue.isEmpty()

True